## Introdução a tensores

In [3]:
import torch

### Criando tensores

* Escalar: valor único (sem dimensão).
* Vetor: coleção de valores (1 dimensão) – por exemplo, um pixel na tela pode ser representado como `X, Y, R, G, B`.
* Matriz: coleção de vetores (2 dimensões) – por exemplo, uma imagem pode ser representada como uma coleção de pixels.
* Tensor: coleção de matrizes (n dimensões) – por exemplo, um GIF pode ser representado como uma coleção de imagens.

In [4]:
scalar = torch.tensor(7)

print(scalar)
print(scalar.ndim)
print(scalar.shape)

tensor(7)
0
torch.Size([])


In [5]:
vector = torch.tensor([3, 4, 5])

print(vector)
print(vector.ndim)
print(vector.shape)

tensor([3, 4, 5])
1
torch.Size([3])


In [6]:
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
2
torch.Size([3, 2])


In [7]:
tensor = torch.tensor([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]],
    [[19, 20], [21, 22], [23, 24]]
])

print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]])
3
torch.Size([4, 3, 2])


In [8]:
print(scalar.item())
print(vector[0])
print(matrix[0])
print(tensor[0])
print(tensor[0][0])
print(tensor[0][0][0])

7
tensor(3)
tensor([1, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 2])
tensor(1)


### Tensores aleatórios

In [9]:
random_tensor = torch.rand(2, 3)

print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.3017, 0.1897, 0.2874],
        [0.2234, 0.2822, 0.7823]])
2
torch.Size([2, 3])


In [10]:
image_tensor = torch.rand(1080, 1920, 3) # 1080p @ 3 cores (R, G, B)

print(image_tensor.ndim)
print(image_tensor.shape)

3
torch.Size([1080, 1920, 3])


### Tensores binários

In [11]:
zeros_tensor = torch.zeros(2, 3)

print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
ones_tensor = torch.ones(2, 3)

print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
print(torch.arange(start=0, end=1000, step=77))
print(torch.arange(start=1, end=10, step=1))
print(torch.zeros_like(torch.arange(start=1, end=10, step=1)))

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tipos de dados

In [14]:
int_tensor = torch.tensor([1, 2, 3])
float_32_tensor = torch.tensor([1, 2.0, 3])
float_64_tensor = torch.tensor([1, 2, 3], dtype=torch.float64)

print(int_tensor, int_tensor.dtype)
print(float_32_tensor, float_32_tensor.dtype)
print(float_64_tensor, float_64_tensor.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32
tensor([1., 2., 3.], dtype=torch.float64) torch.float64


In [15]:
float_16_tensor = float_32_tensor.type(torch.float16)

print(float_16_tensor, float_16_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float16) torch.float16


In [16]:
print((float_16_tensor * float_32_tensor).dtype)

torch.float32


### Informações sobre tensores

* Tipo de dados: `tensor.dtype`
* Formato: `tensor.shape`
* Dispositivo: `tensor.device`

### Manipulando tensores

Operações comuns:

* Adição
* Subtração
* Multiplicação escalar
* Multiplicação matricial

Veja mais informações sobre multiplicação em [How to Multiply Matrices](https://www.mathsisfun.com/algebra/matrix-multiplying.html) e [Matrix Multiplication](http://matrixmultiplication.xyz/).

Para multiplicação matricial, as seguintes regras devem ser observadas:

* As dimensões internas devem ser condizentes:
  - `(3, 2) @ (3, 2)` não funciona
  - `(2, 3) @ (3, 2)` funciona
  - `(3, 2) @ (2, 3)` funciona
* O tensor resultante terá as dimensões das dimensões externas:
  - `(2, 3) @ (3, 2)` resulta em `(2, 2)`
  - `(3, 2) @ (2, 3)` resulta em `(3, 3)`

In [24]:
sample = torch.tensor([1, 2, 3])

print(sample + 10) # torch.add()
print(sample - 10) # torch.sub()
print(sample * 10) # torch.mul()
print(sample @ sample)  # torch.matmul()

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor(14)


Para lidar com erros de dimensão, nós podemos utilizar a transposição matricial. A transposição muda os eixos de um determinado tensor.

In [28]:
tensor_a = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_b = torch.tensor([[0, 1], [2, 3], [4, 5]])

tensor_a @ tensor_b

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [31]:
print(tensor_b, tensor_b.shape)
print(tensor_b.T, tensor_b.T.shape)

tensor([[0, 1],
        [2, 3],
        [4, 5]]) torch.Size([3, 2])
tensor([[0, 2, 4],
        [1, 3, 5]]) torch.Size([2, 3])


In [32]:
tensor_a @ tensor_b.T

tensor([[ 2,  8, 14],
        [ 4, 18, 32],
        [ 6, 28, 50]])