## Introdução a tensores

In [1]:
import torch

### Criando tensores

* Escalar: valor único (sem dimensão).
* Vetor: coleção de valores (1 dimensão) – por exemplo, um pixel na tela pode ser representado como `X, Y, R, G, B`.
* Matriz: coleção de vetores (2 dimensões) – por exemplo, uma imagem pode ser representada como uma coleção de pixels.
* Tensor: coleção de matrizes (n dimensões) – por exemplo, um GIF pode ser representado como uma coleção de imagens.

In [2]:
scalar = torch.tensor(7)

print(scalar)
print(scalar.ndim)
print(scalar.shape)

tensor(7)
0
torch.Size([])


In [3]:
vector = torch.tensor([3, 4, 5])

print(vector)
print(vector.ndim)
print(vector.shape)

tensor([3, 4, 5])
1
torch.Size([3])


In [4]:
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
2
torch.Size([3, 2])


In [5]:
tensor = torch.tensor([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]],
    [[19, 20], [21, 22], [23, 24]]
])

print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]])
3
torch.Size([4, 3, 2])


In [6]:
print(scalar.item())
print(vector[0])
print(matrix[0])
print(tensor[0])
print(tensor[0][0])
print(tensor[0][0][0])

7
tensor(3)
tensor([1, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 2])
tensor(1)


### Tensores aleatórios

In [7]:
random_tensor = torch.rand(2, 3)

print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.6643, 0.2693, 0.6579],
        [0.1999, 0.3974, 0.9432]])
2
torch.Size([2, 3])


In [8]:
image_tensor = torch.rand(1080, 1920, 3) # 1080p @ 3 cores (R, G, B)

print(image_tensor.ndim)
print(image_tensor.shape)

3
torch.Size([1080, 1920, 3])


### Tensores binários

In [9]:
zeros_tensor = torch.zeros(2, 3)

print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
ones_tensor = torch.ones(2, 3)

print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [11]:
print(torch.arange(start=0, end=1000, step=77))
print(torch.arange(start=1, end=10, step=1))
print(torch.zeros_like(torch.arange(start=1, end=10, step=1)))

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tipos de dados

In [12]:
int_tensor = torch.tensor([1, 2, 3])
float_32_tensor = torch.tensor([1, 2.0, 3])
float_64_tensor = torch.tensor([1, 2, 3], dtype=torch.float64)

print(int_tensor, int_tensor.dtype)
print(float_32_tensor, float_32_tensor.dtype)
print(float_64_tensor, float_64_tensor.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32
tensor([1., 2., 3.], dtype=torch.float64) torch.float64


In [13]:
float_16_tensor = float_32_tensor.type(torch.float16)

print(float_16_tensor, float_16_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float16) torch.float16


In [14]:
print((float_16_tensor * float_32_tensor).dtype)

torch.float32


### Informações sobre tensores

* Tipo de dados: `tensor.dtype`
* Formato: `tensor.shape`
* Dispositivo: `tensor.device`

### Manipulando tensores

Operações comuns:

* Adição
* Subtração
* Multiplicação escalar
* Multiplicação matricial

Veja mais informações sobre multiplicação em [How to Multiply Matrices](https://www.mathsisfun.com/algebra/matrix-multiplying.html) e [Matrix Multiplication](http://matrixmultiplication.xyz/).

Para multiplicação matricial, as seguintes regras devem ser observadas:

* As dimensões internas devem ser condizentes:
  - `(3, 2) @ (3, 2)` não funciona
  - `(2, 3) @ (3, 2)` funciona
  - `(3, 2) @ (2, 3)` funciona
* O tensor resultante terá as dimensões das dimensões externas:
  - `(2, 3) @ (3, 2)` resulta em `(2, 2)`
  - `(3, 2) @ (2, 3)` resulta em `(3, 3)`

In [15]:
sample = torch.tensor([1, 2, 3])

print(sample + 10) # torch.add()
print(sample - 10) # torch.sub()
print(sample * 10) # torch.mul()
print(sample @ sample)  # torch.matmul()

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor(14)


Para lidar com erros de dimensão, nós podemos utilizar a transposição matricial. A transposição muda os eixos de um determinado tensor.

In [16]:
tensor_a = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_b = torch.tensor([[0, 1], [2, 3], [4, 5]])

tensor_a @ tensor_b

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [17]:
print(tensor_b, tensor_b.shape)
print(tensor_b.T, tensor_b.T.shape)

tensor([[0, 1],
        [2, 3],
        [4, 5]]) torch.Size([3, 2])
tensor([[0, 2, 4],
        [1, 3, 5]]) torch.Size([2, 3])


In [18]:
tensor_a @ tensor_b.T

tensor([[ 2,  8, 14],
        [ 4, 18, 32],
        [ 6, 28, 50]])

**Curiosidade pessoal:** qual a amplitude resultante ao se adicionar infinitas matrizes aleatórias de intervalo `[0, 1]` (soma de ruídos)? Intuição: tende a ser 1.

**Resposta:** a função `rand()` fo PyTorch gera valores no intervalo `[0, 1)`, não `[0, 1]`. Assim, a pequena possibilidade do valor `1` não ser gerado se acumula ao longo das iterações, gerando uma diferença significativa no final. Mesmo assim, é possível observar que a diferença entre os máximos e mínimos na matriz resultante tende a aumentar e estabilizar-se.

In [19]:
step = 100000
result = torch.zeros(100, 100)

for i in range(0, step * 20):
    if i % step == 0:
        print(f'Epoch {i}, values are: min. {result.min():.1f}; max. {result.max():.1f}; diff. {(result.max() - result.min()):.1f}; weighted diff. {((result.max() - result.min()) / (i / step)):.1f}')

    result += torch.rand(100, 100)

Epoch 0, values are: min. 0.0; max. 0.0; diff. 0.0; weighted diff. nan
Epoch 100000, values are: min. 49681.9; max. 50350.0; diff. 668.1; weighted diff. 668.1
Epoch 200000, values are: min. 99555.4; max. 100602.9; diff. 1047.4; weighted diff. 523.7
Epoch 300000, values are: min. 149401.0; max. 150627.7; diff. 1226.7; weighted diff. 408.9
Epoch 400000, values are: min. 199289.6; max. 200670.6; diff. 1381.0; weighted diff. 345.2
Epoch 500000, values are: min. 249188.2; max. 250787.9; diff. 1599.7; weighted diff. 319.9
Epoch 600000, values are: min. 299137.5; max. 300960.1; diff. 1822.6; weighted diff. 303.8
Epoch 700000, values are: min. 348967.0; max. 350856.1; diff. 1889.1; weighted diff. 269.9
Epoch 800000, values are: min. 398892.0; max. 401020.2; diff. 2128.2; weighted diff. 266.0
Epoch 900000, values are: min. 448914.9; max. 451124.9; diff. 2210.0; weighted diff. 245.6
Epoch 1000000, values are: min. 498860.3; max. 501110.2; diff. 2249.8; weighted diff. 225.0
Epoch 1100000, values 

In [20]:
step = 10000
result = torch.zeros(100, 100, dtype=torch.int)

for i in range(0, step * 20):
    if i % step == 0:
        print(f'Epoch {i}, values are: min. {result.min()}; max. {result.max()}; diff. {(result.max() - result.min())}; weighted diff. {((result.max() - result.min()) / (i / step)):.1f}')

    result += torch.randint(0, 2, (100, 100))

Epoch 0, values are: min. 0; max. 0; diff. 0; weighted diff. nan
Epoch 10000, values are: min. 4833; max. 5177; diff. 344; weighted diff. 344.0
Epoch 20000, values are: min. 9731; max. 10258; diff. 527; weighted diff. 263.5
Epoch 30000, values are: min. 14674; max. 15320; diff. 646; weighted diff. 215.3
Epoch 40000, values are: min. 19597; max. 20392; diff. 795; weighted diff. 198.8
Epoch 50000, values are: min. 24589; max. 25446; diff. 857; weighted diff. 171.4
Epoch 60000, values are: min. 29518; max. 30497; diff. 979; weighted diff. 163.2
Epoch 70000, values are: min. 34471; max. 35590; diff. 1119; weighted diff. 159.9
Epoch 80000, values are: min. 39500; max. 40646; diff. 1146; weighted diff. 143.2
Epoch 90000, values are: min. 44417; max. 45725; diff. 1308; weighted diff. 145.3
Epoch 100000, values are: min. 49402; max. 50765; diff. 1363; weighted diff. 136.3
Epoch 110000, values are: min. 54403; max. 55751; diff. 1348; weighted diff. 122.5
Epoch 120000, values are: min. 59319; ma

### Agregando tensores

Operações comuns:

* Mínimo
* Máximo
* Média
* Soma

In [21]:
sample = torch.arange(0, 100, 10, dtype=torch.float32)

print(sample.min()) # torch.min(sample)
print(sample.max()) # torch.max(sample)
print(sample.mean()) # torch.mean(sample)
print(sample.sum()) # torch.sum(sample)

tensor(0.)
tensor(90.)
tensor(45.)
tensor(450.)


### Encontrando mínimos e máximos posicionais

In [22]:
print(sample.argmin())
print(sample.argmax())

tensor(0)
tensor(9)


### Alterando a forma dos tensores

* _Reshaping_: altera a forma do tensor.
* _View_: vista de determinado tensor, compartilhando o objeto na memória.
* _Stacking_: sobrepõe os tensores em determinada dimensão.
* _Squeeze_: remove dimensões vazias.
* _Unsqueeze_: adiciona dimensões vazias em determinada dimensão.
* _Permute_: altera a ordem das dimensões (retorna uma `view` do tensor original).

In [23]:
print(sample)
print(sample.shape)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])
torch.Size([10])


In [24]:
reshaped = sample.reshape(2, 5)

print(reshaped)
print(reshaped.shape)

tensor([[ 0., 10., 20., 30., 40.],
        [50., 60., 70., 80., 90.]])
torch.Size([2, 5])


In [25]:
reshaped = sample.reshape(5, 2)

print(reshaped)
print(reshaped.shape)

tensor([[ 0., 10.],
        [20., 30.],
        [40., 50.],
        [60., 70.],
        [80., 90.]])
torch.Size([5, 2])


In [26]:
reshaped = sample.reshape(10, 1)

print(reshaped)
print(reshaped.shape)

tensor([[ 0.],
        [10.],
        [20.],
        [30.],
        [40.],
        [50.],
        [60.],
        [70.],
        [80.],
        [90.]])
torch.Size([10, 1])


In [27]:
view = sample.view(2, 5)

print(sample)
print(view)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])
tensor([[ 0., 10., 20., 30., 40.],
        [50., 60., 70., 80., 90.]])


In [28]:
view[:, 0] = 5

print(sample)
print(view)

tensor([ 5., 10., 20., 30., 40.,  5., 60., 70., 80., 90.])
tensor([[ 5., 10., 20., 30., 40.],
        [ 5., 60., 70., 80., 90.]])


In [29]:
print(torch.stack([sample, sample, sample], dim=0))
print(torch.stack([sample, sample, sample], dim=1))

tensor([[ 5., 10., 20., 30., 40.,  5., 60., 70., 80., 90.],
        [ 5., 10., 20., 30., 40.,  5., 60., 70., 80., 90.],
        [ 5., 10., 20., 30., 40.,  5., 60., 70., 80., 90.]])
tensor([[ 5.,  5.,  5.],
        [10., 10., 10.],
        [20., 20., 20.],
        [30., 30., 30.],
        [40., 40., 40.],
        [ 5.,  5.,  5.],
        [60., 60., 60.],
        [70., 70., 70.],
        [80., 80., 80.],
        [90., 90., 90.]])


In [30]:
print(torch.tensor([[[[1, 0, 6, 5, 7]]]]).squeeze())

tensor([1, 0, 6, 5, 7])


In [31]:
print(sample.unsqueeze(0))
print(sample.unsqueeze(1))

tensor([[ 5., 10., 20., 30., 40.,  5., 60., 70., 80., 90.]])
tensor([[ 5.],
        [10.],
        [20.],
        [30.],
        [40.],
        [ 5.],
        [60.],
        [70.],
        [80.],
        [90.]])


In [56]:
print(image_tensor.size())
print(image_tensor.permute(2, 0, 1).size())

torch.Size([1080, 1920, 3])
torch.Size([3, 1080, 1920])


### Selecionando dados de tensores

* Indexação

In [57]:
data = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(data)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [58]:
print(data[0])
print(data[0][0])
print(data[:, 0])
print(data[:][0])
print(data[:][:][:][:][0])

tensor([1, 2, 3])
tensor(1)
tensor([1, 4, 7])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [59]:
print(data[0, 1:])
print(data[0, :1])
print(data[1:, 0])
print(data[1:, 1])
print(data[1:, 1:])

tensor([2, 3])
tensor([1])
tensor([4, 7])
tensor([5, 8])
tensor([[5, 6],
        [8, 9]])
