## Introdução a tensores

In [103]:
import torch

### Criando tensores

* Escalar: valor único (sem dimensão).
* Vetor: coleção de valores (1 dimensão) – por exemplo, um pixel na tela pode ser representado como `X, Y, R, G, B`.
* Matriz: coleção de vetores (2 dimensões) – por exemplo, uma imagem pode ser representada como uma coleção de pixels.
* Tensor: coleção de matrizes (n dimensões) – por exemplo, um GIF pode ser representado como uma coleção de imagens.

In [104]:
scalar = torch.tensor(7)

print(scalar)
print(scalar.ndim)
print(scalar.shape)

tensor(7)
0
torch.Size([])


In [105]:
vector = torch.tensor([3, 4, 5])

print(vector)
print(vector.ndim)
print(vector.shape)

tensor([3, 4, 5])
1
torch.Size([3])


In [106]:
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])

print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
2
torch.Size([3, 2])


In [107]:
tensor = torch.tensor([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]],
    [[19, 20], [21, 22], [23, 24]]
])

print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]])
3
torch.Size([4, 3, 2])


In [108]:
print(scalar.item())
print(vector[0])
print(matrix[0])
print(tensor[0])
print(tensor[0][0])
print(tensor[0][0][0])

7
tensor(3)
tensor([1, 2])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 2])
tensor(1)


### Tensores aleatórios

In [109]:
random_tensor = torch.rand(2, 3)

print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.shape)

tensor([[0.0182, 0.0120, 0.3754],
        [0.0782, 0.1555, 0.0537]])
2
torch.Size([2, 3])


In [110]:
image_tensor = torch.rand(1080, 1920, 3) # 1080p @ 3 cores (R, G, B)

print(image_tensor.ndim)
print(image_tensor.shape)

3
torch.Size([1080, 1920, 3])


### Tensores binários

In [111]:
zeros_tensor = torch.zeros(2, 3)

print(zeros_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [112]:
ones_tensor = torch.ones(2, 3)

print(ones_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [113]:
print(torch.arange(start=0, end=1000, step=77))
print(torch.arange(start=1, end=10, step=1))
print(torch.zeros_like(torch.arange(start=1, end=10, step=1)))

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tipos de dados

In [114]:
int_tensor = torch.tensor([1, 2, 3])
float_32_tensor = torch.tensor([1, 2.0, 3])
float_64_tensor = torch.tensor([1, 2, 3], dtype=torch.float64)

print(int_tensor, int_tensor.dtype)
print(float_32_tensor, float_32_tensor.dtype)
print(float_64_tensor, float_64_tensor.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32
tensor([1., 2., 3.], dtype=torch.float64) torch.float64


In [115]:
float_16_tensor = float_32_tensor.type(torch.float16)

print(float_16_tensor, float_16_tensor.dtype)

tensor([1., 2., 3.], dtype=torch.float16) torch.float16


In [116]:
print((float_16_tensor * float_32_tensor).dtype)

torch.float32


### Informações sobre tensores

* Tipo de dados: `tensor.dtype`
* Formato: `tensor.shape`
* Dispositivo: `tensor.device`